### ISSUE TITLE
Using nnUnet features

### ISSUE THREAD

**Issue by annareithmeir** [multimodallearning/convexAdam#10]
Thanks for the repo! 

How exactly do you use the nnUnet features?
It seems that in convexAdam_nnUNet.py you load the already computed features. 

Which exact nnUnet version did you use and do you have a code snippet available that shows how you obtained the features?

**Comment by mattiaspaul** [comment]
Dear Anna, currently we do not provide an automatic computation of the nnUNet features but rely (as you noticed) on pre-computed predictions. This is because they have to be task specific. In the future we are planning to incorporate at least a basic CT model (e.g. TotalSegmentator). Currently you can simply follow the instructions on https://github.com/MIC-DKFZ/nnUNet to download pre-trained weights and perform inference on the intended task. 
Best wishes, Mattias
